/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClientDatabase": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "CommunicationLogGroup": {
      "name": string
      "type": "aws.cloudwatch/logGroup.LogGroup"
    }
    "CommunicationLogStream": {
      "name": string
      "type": "aws.cloudwatch/logStream.LogStream"
    }
    "DLQLogGroup": {
      "name": string
      "type": "aws.cloudwatch/logGroup.LogGroup"
    }
    "DLQLogStream": {
      "name": string
      "type": "aws.cloudwatch/logStream.LogStream"
    }
    "DatabaseVPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "EmailSenderKey": {
      "arn": string
      "type": "aws.kms/key.Key"
    }
    "EmailSenderKeyAlias": {
      "alias": string
      "type": "aws.kms/alias.Alias"
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "IdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "InternalNightmareApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "LambdaLogGroup": {
      "name": string
      "type": "aws.cloudwatch/logGroup.LogGroup"
    }
    "LambdaLogStream": {
      "name": string
      "type": "aws.cloudwatch/logStream.LogStream"
    }
    "LoggingDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "LoggingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainframeIpAddress": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainframePassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainframeUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Region": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "RootUserEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RootUserPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UserGroups": {
      "admin": string
      "agent": string
      "rootAdmin": string
      "type": "sst.sst.Linkable"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "UserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
