/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClientDatabase": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "sst.aws.Postgres"
      "username": string
    }
    "DatabaseVPC": {
      "type": "sst.aws.Vpc"
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "IdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "LoggingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Logs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Region": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "RootUserEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RootUserPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Transactions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UserGroups": {
      "admin": string
      "agent": string
      "rootAdmin": string
      "type": "sst.sst.Linkable"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "UserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
